INSERT INTO COLONISTS(PROFILE_NAME, INTERGALACTIC_ID, PASSWORD_HASH)
VALUES ('The Super User', 'admin', '$2a$10$789sl.j5FmcwKeYwoqJE8.HDsgST4v5tmWSKroC3N8EWdVlaXPpDi');

INSERT INTO ROLES(INTERGALACTIC_ID, ROLE)
VALUES ('admin', 'ADMIN');
